Repository JSD-0423/frontend-final-2, pull requests merged in 2023-07, with the labels that each got.

#7 Banner section
  src/App.jsx
  src/assets/images/facepacks.png
  src/assets/images/herosection.png
  src/assets/images/plainSlide.png
  src/assets/images/skincare.png
  src/components/plain-content/index.jsx
  src/components/plain-slide/index.jsx
  src/pages/home/banner-section/index.jsx
Labels: approved

#6 Links
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/assets/icons/PWA eCommerce Theme (Community) (3).zip
  src/assets/icons/PWA eCommerce Theme (Community) (4).zip
  src/assets/icons/heart-primary.svg
  src/assets/icons/heart-secondary.svg
  src/assets/images/purse.png
  src/components/footer/index.jsx
  src/components/horizontal-scroll-section/index.jsx
  src/components/horizontal-scroll-section/styles.js
  src/components/inputs/default-input/index.jsx
  src/components/inputs/icon-input/index.jsx
  src/components/inputs/icon-input/styles.js
  src/components/inputs/plain-input/index.jsx
  src/components/inputs/plain-input/styles.js
  src/components/inputs/styles.js
  src/components/links/action-link/index.jsx
  src/components/links/action-link/styles.js
  src/components/links/nav-link/index.jsx
  src/components/links/nav-link/styles.js
  src/components/links/styles.js
  src/components/price/final-price/index.jsx
  src/components/unfocused-croursal/styles.js
  src/pages/home/index.jsx
  src/themes/theme.js
Labels: fix-conflict

#8 Inputs
  src/App.jsx
  src/themes/theme.js
Labels: fix-conflict

#14 Header
  public/images/laura.png
  src/App.jsx
  src/components/brand-item/styles.js
  src/components/header/drawer.jsx
  src/components/header/index.jsx
  src/components/inputs/default-input/index.jsx
  src/components/product-with-title/index.jsx
  src/components/product-with-title/styles.js
  src/pages/home/brands-section/index.jsx
  src/pages/home/handpicked-section/index.jsx
  src/pages/home/index.jsx
  src/pages/home/new-arrivals-section/index.jsx
  src/themes/theme.js
Labels: requested-changes
